title: "In bici per l'italia"
description: ""
baseurl: "/inbiciperlitalia"
url: "https://pmod04.github.io"

# Tema e build
markdown: kramdown
highlighter: rouge
permalink: /articoli/:year/:month/:day/:title/

# Kramdown: supporta immagini e tabelle
kramdown:
  input: GFM
  hard_wrap: false

# Plugin supportati da GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Escludi dalla build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
